### PR TITLE
Support asymmetric algorithms

### PR DESCRIPTION
**Pull request by norydev**
## Description

For asymmetric algorithms, the decoding secret is different than the encoding secret. This change adds support for an optional decoding secret configuration.

### CODE REVIEW

**Comment by norydev** [comment]
Reason for PR: I would love to be able to use this library with RS256 algorithm, which necessitates this change.

**Review by waiting-for-dev — APPROVED** [review]
Awesome! Thanks for your collaboration. Do you need a new release with this change?

**Comment by waiting-for-dev** [comment]
Released in v0.7.0! 🚀

**Comment by Eric-Guo** [comment]
I just upgrade to 0.7.0 today and find it maybe [having a break change](https://github.com/thape-cn/oauth2id/commit/f7d273bf6e8efd64bec91f7cc940dcb9af93faf8), I'm not yet check it, but I'm sure in client code side, it must do some configuration.

**Comment by waiting-for-dev** [comment]
Please, report if you find more details. Thanks!

**Comment by krnjn** [comment]
I also encountered a breaking change with this here -- is there some configuration change we need to make in order to be compatible with the change introduced in this PR? Effectively, the JWT strategy no longer works in our case. I can dig in more later, but am happy to introduce an update / config change if there's a suggested one to comply with this new feature.

**Comment by waiting-for-dev** [comment]
Please, see https://github.com/waiting-for-dev/devise-jwt/pull/250

**Pull request merged**
