### PR TITLE
feat: use Zeitwerk to load gem structure

### PR DESCRIPTION
**Pull request by seuros**
dry-rb use zeitwerk as loader starting from version 1.0.0

I leveraged it usage to make it work in this gem.

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
Thanks, I'll look into it as soon as possible.

**Comment by thomasdarde** [comment]
This branch works nice for us in case it helps merging it

**Comment by dmitry** [comment]
@waiting-for-dev please let us know if it's still required some work for this PR.

**Comment by waiting-for-dev** [comment]
Many thanks for your collaboration. TBH, I don't feel comfortable adding Zeitwerk as a dependency. I know it's already transitive through dry-*, but I don't think adding the complexity here pays off. WDYT?

(I'm ok relaxing dry-* requirements, though, I already commented in the referenced PR)

**Comment by seuros** [comment]
@waiting-for-dev , I did notice a slight performance speed in testing by bumping to dry 1.0. (classes are loaded only when needed)
This is the reason I think we should start encouraging other devs to keep their dependencies up to date.

**Comment by waiting-for-dev** [comment]
To be clear, I'm ok bumping to dry 1.0 (not only ok, we need to do it), but I'm not sure about using Zeitwerk here.

**Comment by thomasdarde** [comment]
Hi @waiting-for-dev , do you have any news on this 1.0 release schedule ?

**Comment by waiting-for-dev** [comment]
> Hi @waiting-for-dev , do you have any news on this 1.0 release schedule ?

I just released warden-jwt_auth v0.8.0 🥳 

I'll close this PR for now, but I might reconsider it in the future. Thanks again for your contribution.

**Pull request closed without merging**
